server:
  port: 8091

spring:
  application:
    name: canary-consumer
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address:  https://cse.cn-north-4.myhuaweicloud.com
        appName: dhcc-example
        serviceName: canary-consumer
        version: 0.0.2
        healthCheckInterval: 30
        autoDiscovery: true
      credentials:
        enabled: true
        accessKey: BE1AYAXIXO1EHSQKQG8U
        secretKey: YfaypJBG9o8nf3aoyBlgw1dDVOrQ4e9ecvDOmhXo
        akskCustomCipher: default
        project: cn-north-4

servicecomb:
  routeRule:
    canary-provider: |
      - precedence: 1 #优先级
        route: #路由规则
          - weight: 80
            tags:
              version: 0.0.1
          - weight: 20
            tags:
              version: 0.0.2